blank_issues_enabled: false
contact_links:
  - name: Güvenlik açığı bildir
    url: https://github.com/zestoles/zestoles-desktop/security/advisories/new
    about: Güvenlik açıklarını özel olarak bildirin.
